# Dependencies of this repo (not an inventory of the machine)

tap "raine/workmux"

brew "fd"
brew "fish"
brew "fnm"
brew "gh"
brew "git-delta"
brew "git-lfs"
brew "jq"
brew "neovim"
brew "pre-commit"
brew "raine/workmux/workmux"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tree-sitter-cli"
cask "font-fira-mono-nerd-font"
cask "ghostty"
cask "secretive"
